#!/usr/bin/env python3
"""Generate api_hooks.h: every traceENTER_* / traceRETURN_* default in the
pinned FreeRTOS.h, redefined to call the two-core port's API-boundary hooks.

The two-core sim contract ends a turn at a top-level kernel call, so the port
has to see EVERY public call's entry and return. FreeRTOS V11 provides a
trace macro pair for each one (~400 of them); writing them by hand would miss
some, and a missed one is a call the port cannot see. Generated from the
pinned kernel, so the set is exactly that kernel's.

    python3 gen_api_hooks.py ../FreeRTOS-Kernel/include/FreeRTOS.h > api_hooks.h
"""
import re
import sys

src = open(sys.argv[1], encoding="utf-8").read()
# Kernel-internal entry points that carry trace macros but are not calls a
# task makes: `taskYIELD_WITHIN_API()` is `vTaskYieldWithinAPI()` on SMP, and
# the timer daemon reaches it from its own loop at depth zero. Hooking it
# would end a turn between `xTaskResumeAll` and the yield that follows it,
# which the Rust side takes as one step.
INTERNAL = {"vTaskYieldWithinAPI"}
seen = set()
out = [
    "/* GENERATED by gen_api_hooks.py from the pinned FreeRTOS.h. Do not edit. */",
    "#ifndef KAIROS_API_HOOKS_H",
    "#define KAIROS_API_HOOKS_H",
]
for m in re.finditer(r"#define\s+(trace(ENTER|RETURN)_\w+)\s*\(([^)]*)\)", src):
    name, kind, args = m.group(1), m.group(2), m.group(3).strip()
    if name in seen or name.split("_", 1)[1] in INTERNAL:
        continue
    seen.add(name)
    hook = "vPortApiEnter()" if kind == "ENTER" else "vPortApiReturn()"

    out.append(f"#define {name}( {args} )    {hook}" if args else f"#define {name}()    {hook}")
out.append("#endif")
print("\n".join(out))
print(f"/* {len(seen)} macros */")
