#!/usr/bin/env python3
"""Derive the two-core FreeRTOSConfig.h from the one-core harness's.

Same configuration and the same trace contract, so the two corpora cannot
drift apart by hand-editing. What changes:
  - configNUMBER_OF_CORES 2, configRUN_MULTIPLE_PRIORITIES 1, the passive
    idle hook on, no core affinity;
  - every traceENTER_* / traceRETURN_* goes to the port (api_hooks.h)
    instead of the one-core patch's two stream-buffer hooks;
  - the events that mean "this call has blocked" also tell the port, which
    is how it knows a call it parks inside will be RE-MADE on the Rust side
    rather than finished.

    python3 gen_config.py ../harness/FreeRTOSConfig.h > FreeRTOSConfig.h
"""
import re
import sys

s = open(sys.argv[1], encoding="utf-8").read().replace("\r\n", "\n")

# The one-core contract v2 stream-buffer hooks: the generated header has
# them, and every other call's, so this block goes.
start = s.index("extern void vPortKairosApiEnter( void );")
end = s.index("traceRETURN_xStreamBufferReceive")
end = s.index("\n", end) + 1
s = s[:start] + s[end:]

s = s.replace(
    '#include "kairos_trace.h"\n',
    '#include "kairos_trace.h"\n#include "api_hooks.h"\n\n'
    "/* Two cores (see portmacro.h for the two-core sim contract). */\n"
    "#define configNUMBER_OF_CORES                      2\n"
    "#define configRUN_MULTIPLE_PRIORITIES              1\n"
    "#define configUSE_CORE_AFFINITY                    0\n"
    "#define configUSE_PASSIVE_IDLE_HOOK                1\n"
    "#define configTIMER_SERVICE_TASK_CORE_AFFINITY     tskNO_AFFINITY\n",
    1,
)

BLOCKS = [
    "traceBLOCKING_ON_QUEUE_SEND",
    "traceBLOCKING_ON_QUEUE_RECEIVE",
    "traceBLOCKING_ON_QUEUE_PEEK",
    "traceTASK_NOTIFY_WAIT_BLOCK",
    "traceTASK_NOTIFY_TAKE_BLOCK",
    "traceEVENT_GROUP_WAIT_BITS_BLOCK",
]
for name in BLOCKS:
    m = re.search(r"#define " + name + r"(\([^)]*\))(\s+)(.*)\n", s)
    assert m, name
    s = s[: m.start()] + f"#define {name}{m.group(1)}{m.group(2)}do {{ vPortBlocking(); {m.group(3)}; }} while( 0 )\n" + s[m.end():]

print("/* GENERATED by gen_config.py from ../harness/FreeRTOSConfig.h. Do not edit. */")
print(s, end="")
