//! `kairos harden` — render the hardening-status block into a README from its
//! `docs/plans/use-protection-please.md`.
//!
//! The plan file is the single source of truth; this verb is the only writer
//! of the README block. It is idempotent: running it twice produces a
//! byte-identical README, which is what makes `--check` usable as a CI gate.
//!
//! A Rust port of the `use-protection-please` skill's
//! `scripts/render_readme_table.py` (2026-08-18), rendering the block the
//! skill's `templates/readme-table.md` specifies, so plan files stay
//! interchangeable with every other unit in the portfolio. Glyphs are written
//! as `\u{..}` escapes so this file stays ASCII.

use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
};

use crate::{Manifest, Result, fail, has_flag, option};

pub(crate) const PLAN_NAME: &str = "use-protection-please.md";

const BEGIN: &str = "<!-- HARDENING-TABLE:BEGIN";
const END: &str = "<!-- HARDENING-TABLE:END -->";
const BEGIN_LINE: &str = "<!-- HARDENING-TABLE:BEGIN generated by use-protection-please \u{2014} edit docs/plans/use-protection-please.md, not this block -->";
const BAR_CELLS: usize = 20;
const STAR: char = '\u{2605}';
const FULL: char = '\u{2588}';
const EMPTY: char = '\u{2591}';
const GLYPH_DONE: &str = "\u{2705}";
const GLYPH_SCHEDULED: &str = "\u{1F5D3}";
const GLYPH_OPEN: &str = "\u{2B1C}";
const DASH: &str = "\u{2014}";
const DOT: &str = "\u{b7}";

/// Compliance frameworks and the gates that carry their technical controls
/// (shared reference data; which frameworks are in scope is per unit).
const FRAMEWORKS: [(&str, &str, &str); 6] = [
    (
        "soc2",
        "SOC 2",
        "H-01 H-02 H-07 H-08 H-09 H-10 H-11 H-12 H-13 H-18 H-19 H-22 H-26 H-27 H-33 H-37 H-38 H-39 C-01 C-02 C-03 C-07 C-09 C-10 C-11 C-12 C-13",
    ),
    (
        "pci-dss",
        "PCI DSS v4.0",
        "H-07 H-08 H-09 H-12 H-15 H-16 H-18 H-19 H-26 H-27 H-34 H-35 C-01 C-03 C-04 C-05 C-07 C-08 C-09",
    ),
    (
        "gdpr-pii",
        "GDPR / PII",
        "H-01 H-20 H-34 H-35 H-39 C-01 C-02 C-03 C-04 C-05 C-06 C-07 C-08 C-09 C-10 C-11",
    ),
    ("hipaa", "HIPAA", "H-07 H-12 C-03 C-04 C-07 C-09"),
    (
        "eu-cra",
        "EU CRA",
        "H-04 H-05 H-09 H-12 H-15 H-33 H-39 H-40 C-11 C-14",
    ),
    (
        "nist-ssdf",
        "NIST SSDF",
        "H-03 H-04 H-06 H-08 H-09 H-10 H-12 H-13 H-15 H-22 H-23 H-26 H-27 H-28 H-32 H-38 H-40 C-12 C-14",
    ),
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Status {
    Completed,
    Scheduled,
    Incomplete,
    NotApplicable,
}

impl Status {
    fn parse(raw: &str) -> Result<Self> {
        let token: String = raw
            .trim()
            .trim_matches(|c: char| matches!(c, '`' | '*' | '_' | ' '))
            .trim_end_matches('.')
            .chars()
            .filter(|c| c.is_ascii_alphabetic() || *c == '/' || *c == ' ')
            .collect();
        let folded: String = token.to_lowercase().chars().filter(|c| *c != ' ').collect();
        match folded.as_str() {
            "na" | "n/a" | "notapplicable" => Ok(Self::NotApplicable),
            "completed" => Ok(Self::Completed),
            "scheduled" => Ok(Self::Scheduled),
            "incomplete" | "" => Ok(Self::Incomplete),
            _ => fail(format!(
                "unrecognised status {raw:?} (expected one of Completed, Scheduled, Incomplete, N/A)"
            )),
        }
    }
}

#[derive(Debug, Clone)]
struct Row {
    id: String,
    gate: String,
    status: Status,
    target: String,
    phase: String,
    star: bool,
}

#[derive(Debug, Default)]
struct Counts {
    completed: usize,
    scheduled: usize,
    incomplete: usize,
    na: usize,
}

impl Counts {
    fn add(&mut self, s: Status) {
        match s {
            Status::Completed => self.completed += 1,
            Status::Scheduled => self.scheduled += 1,
            Status::Incomplete => self.incomplete += 1,
            Status::NotApplicable => self.na += 1,
        }
    }
}

struct Plan {
    meta: BTreeMap<String, String>,
    rows: Vec<Row>,
    warnings: Vec<String>,
}

// ---------------------------------------------------------------- parsing --

fn split_row(line: &str) -> Vec<String> {
    let body = line.trim();
    let body = body.strip_prefix('|').unwrap_or(body);
    let body = body.strip_suffix('|').unwrap_or(body);
    body.split('|').map(|c| c.trim().to_owned()).collect()
}

fn is_gate_id(cell: &str) -> bool {
    let mut chars = cell.chars();
    matches!(chars.next(), Some('H' | 'C'))
        && chars.next() == Some('-')
        && chars.clone().count() > 0
        && chars.all(|c| c.is_ascii_digit())
}

/// `**Key**: value` header lines above the checklist.
fn meta_line(line: &str) -> Option<(String, String)> {
    let rest = line.strip_prefix("**")?;
    let end = rest.find("**")?;
    let key = &rest[..end];
    if key.is_empty()
        || !key
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == ' ' || c == '.')
    {
        return None;
    }
    let value = rest[end + 2..].trim_start();
    let value = value.strip_prefix(':').unwrap_or(value).trim();
    Some((key.trim().to_lowercase(), value.to_owned()))
}

fn parse_plan(path: &Path) -> Result<Plan> {
    let text = fs::read_to_string(path)?;
    let mut meta = BTreeMap::new();
    let mut rows: Vec<Row> = Vec::new();
    let mut warnings = Vec::new();
    let mut phase = "Unfiled".to_owned();
    let mut in_checklist = false;

    for line in text.lines() {
        if line.starts_with("## ") {
            in_checklist = line.trim().to_lowercase().starts_with("## checklist");
            continue;
        }
        if let Some(h) = line.strip_prefix("### ") {
            phase = h.trim().to_owned();
            continue;
        }
        if rows.is_empty() {
            if let Some((k, v)) = meta_line(line) {
                meta.entry(k).or_insert(v);
            }
        }
        if !in_checklist || !line.trim_start().starts_with('|') {
            continue;
        }
        let cells = split_row(line);
        let Some(id) = cells.first() else { continue };
        if !is_gate_id(id) {
            continue;
        }
        if cells.len() < 3 {
            return fail(format!(
                "{}: malformed row: {}",
                path.display(),
                line.trim()
            ));
        }
        if rows.iter().any(|r| &r.id == id) {
            return fail(format!("{}: duplicate gate {id}", path.display()));
        }
        let gate = cells.get(1).cloned().unwrap_or_default();
        let mut status = Status::parse(cells.get(2).map_or("", String::as_str))?;
        let evidence = cells.get(3).cloned().unwrap_or_default();
        let target = cells.get(4).cloned().unwrap_or_default();
        if status == Status::Scheduled && target.is_empty() {
            warnings.push(format!(
                "{id}: Scheduled with no Target date -> counted Incomplete"
            ));
            status = Status::Incomplete;
        }
        if status == Status::NotApplicable && evidence.is_empty() {
            warnings.push(format!("{id}: N/A with no reason in Evidence"));
        }
        rows.push(Row {
            id: id.clone(),
            star: gate.contains(STAR),
            gate,
            status,
            target,
            phase: phase.clone(),
        });
    }
    if rows.is_empty() {
        return fail(format!(
            "{}: no gate rows found (expected rows starting '| H-01 |')",
            path.display()
        ));
    }
    Ok(Plan {
        meta,
        rows,
        warnings,
    })
}

// -------------------------------------------------------------- rendering --

/// Keep the label at the head of a prose header field, drop the gloss after it.
fn lead_token(raw: &str, default: &str, stops: &[&str]) -> String {
    let mut val = raw.trim().to_owned();
    for sep in stops {
        if let Some(i) = val.find(sep) {
            val.truncate(i);
        }
    }
    val.split_whitespace()
        .next()
        .map_or_else(|| default.to_owned(), str::to_owned)
}

fn phase_label(heading: &str) -> String {
    let rest = heading.strip_prefix("Phase").unwrap_or(heading);
    rest.trim().to_owned()
}

fn clean_gate(gate: &str) -> String {
    gate.replace(STAR, "").trim().to_owned()
}

fn progress_bar(fraction: f64) -> String {
    #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
    let filled = ((fraction * BAR_CELLS as f64) as usize).min(BAR_CELLS);
    let mut s = String::with_capacity(BAR_CELLS * 3);
    for _ in 0..filled {
        s.push(FULL);
    }
    for _ in filled..BAR_CELLS {
        s.push(EMPTY);
    }
    s
}

/// The plan's path relative to the README's directory, forward slashes.
fn rel_link(readme: &Path, plan: &Path) -> String {
    let base = readme.parent().unwrap_or_else(|| Path::new("."));
    let (Ok(base), Ok(plan_abs)) = (base.canonicalize(), plan.canonicalize()) else {
        return plan.to_string_lossy().replace('\\', "/");
    };
    match plan_abs.strip_prefix(&base) {
        Ok(rel) => rel.to_string_lossy().replace('\\', "/"),
        Err(_) => plan.to_string_lossy().replace('\\', "/"),
    }
}

fn compliance_rows(plan: &Plan) -> Vec<(String, usize, usize, &'static str)> {
    let declared = plan
        .meta
        .get("compliance")
        .map(|s| s.to_lowercase())
        .unwrap_or_default();
    let declared = if declared.trim().starts_with("none") {
        declared.split('-').next().unwrap_or_default().to_owned()
    } else {
        declared
    };
    let mut out = Vec::new();
    for (fid, label, gates) in FRAMEWORKS {
        if !declared.contains(fid) {
            continue;
        }
        let live: Vec<&Row> = gates
            .split_whitespace()
            .filter_map(|g| plan.rows.iter().find(|r| r.id == g))
            .filter(|r| r.status != Status::NotApplicable)
            .collect();
        if live.is_empty() {
            continue;
        }
        let met = live
            .iter()
            .filter(|r| r.status == Status::Completed)
            .count();
        let mark = if met == live.len() {
            GLYPH_DONE
        } else if live.iter().any(|r| r.status == Status::Scheduled) {
            GLYPH_SCHEDULED
        } else {
            GLYPH_OPEN
        };
        out.push((label.to_owned(), met, live.len(), mark));
    }
    out
}

fn render_block(
    plan: &Plan,
    readme: &Path,
    plan_path: &Path,
    link: &str,
    architect: &str,
) -> String {
    let mut counts = Counts::default();
    let mut per_phase: Vec<(String, Counts)> = Vec::new();
    for row in &plan.rows {
        counts.add(row.status);
        match per_phase.iter_mut().find(|(p, _)| *p == row.phase) {
            Some((_, c)) => c.add(row.status),
            None => {
                let mut c = Counts::default();
                c.add(row.status);
                per_phase.push((row.phase.clone(), c));
            }
        }
    }
    let tracked = counts.completed + counts.scheduled + counts.incomplete;
    #[allow(clippy::cast_precision_loss)]
    let pct = if tracked == 0 {
        0.0
    } else {
        counts.completed as f64 / tracked as f64
    };
    let stars: Vec<&Row> = plan
        .rows
        .iter()
        .filter(|r| r.star && r.status != Status::NotApplicable)
        .collect();
    let stars_done = stars
        .iter()
        .filter(|r| r.status == Status::Completed)
        .count();

    let meta = |k: &str| plan.meta.get(k).map_or("", String::as_str);
    let tier = lead_token(
        meta("tier"),
        "unspecified",
        &[" - ", " \u{2014} ", " (", ","],
    );
    let audited = lead_token(meta("audited"), "unrecorded", &[" by "]);
    let depth = lead_token(meta("audit depth"), "", &[" - ", " \u{2014} ", " (", ","]);
    let audited_str = if depth.is_empty() {
        audited
    } else {
        format!("{audited} ({depth})")
    };
    let link = if link.is_empty() {
        rel_link(readme, plan_path)
    } else {
        link.to_owned()
    };

    #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
    let pct_int = (pct * 100.0).round() as usize;
    let mut out = vec![
        BEGIN_LINE.to_owned(),
        "## Hardening status".to_owned(),
        String::new(),
        format!(
            "**Tier** {tier} {DOT} **Audited** {audited_str} {DOT} **v1.0.0 gates** {stars_done}/{} {DOT} [Full checklist]({link})",
            stars.len()
        ),
        String::new(),
        format!(
            "`{}` **{pct_int}%** &nbsp;{DOT}&nbsp; {} Completed {DOT} {} Scheduled {DOT} {} Incomplete {DOT} {} N/A",
            progress_bar(pct),
            counts.completed,
            counts.scheduled,
            counts.incomplete,
            counts.na
        ),
        String::new(),
        format!(
            "| Phase | {GLYPH_DONE} Completed | {GLYPH_SCHEDULED} Scheduled | {GLYPH_OPEN} Incomplete | {DOT} N/A |"
        ),
        "|---|--:|--:|--:|--:|".to_owned(),
    ];
    for (phase, c) in &per_phase {
        out.push(format!(
            "| {} | {} | {} | {} | {} |",
            phase_label(phase),
            c.completed,
            c.scheduled,
            c.incomplete,
            c.na
        ));
    }
    out.push(format!(
        "| **Total** | **{}** | **{}** | **{}** | **{}** |",
        counts.completed, counts.scheduled, counts.incomplete, counts.na
    ));

    let mut upcoming: Vec<&Row> = plan
        .rows
        .iter()
        .filter(|r| r.status == Status::Scheduled)
        .collect();
    upcoming.sort_by(|a, b| (&a.target, &a.id).cmp(&(&b.target, &b.id)));
    upcoming.truncate(3);
    if !upcoming.is_empty() {
        let items: Vec<String> = upcoming
            .iter()
            .map(|r| format!("{} {} ({})", r.id, clean_gate(&r.gate), r.target))
            .collect();
        out.push(String::new());
        out.push(format!(
            "**Next up** {DASH} {}",
            items.join(&format!(" {DOT} "))
        ));
    }

    let comp = compliance_rows(plan);
    if !comp.is_empty() {
        out.push(String::new());
        out.push(format!(
            "**Compliance** {DASH} *technical controls evidenced by this audit. NOT a certification, an attestation, or an auditor's opinion.*"
        ));
        out.push(String::new());
        out.push("| Framework | Technical controls met | |".to_owned());
        out.push("|---|--:|:--|".to_owned());
        for (label, met, total, mark) in comp {
            out.push(format!("| {label} | {met} / {total} | {mark} |"));
        }
    }

    let who = if architect.is_empty() {
        meta("architect").trim().to_owned()
    } else {
        architect.trim().to_owned()
    };
    if !who.is_empty() {
        out.push(String::new());
        out.push(format!("**Architect** {DASH} {who}"));
    }
    out.push(END.to_owned());
    out.join("\n")
}

fn splice(readme: &str, block: &str) -> String {
    if let (Some(start), Some(end)) = (readme.find(BEGIN), readme.find(END)) {
        if end > start {
            return format!("{}{block}{}", &readme[..start], &readme[end + END.len()..]);
        }
    }
    let body = readme.trim_end_matches('\n');
    if body.is_empty() {
        format!("{block}\n")
    } else {
        format!("{body}\n\n---\n\n{block}\n")
    }
}

// ---------------------------------------------------------------- driving --

/// Render one plan into one README. With `check`, a stale README is an error
/// and nothing is written. Returns `Ok(true)` when the README changed (or
/// would change).
pub(crate) fn process(
    plan_path: &Path,
    readme: &Path,
    check: bool,
    link: &str,
    architect: &str,
) -> Result<bool> {
    let plan = parse_plan(plan_path)?;
    for w in &plan.warnings {
        eprintln!("  ! {}: {w}", plan_path.display());
    }
    let block = render_block(&plan, readme, plan_path, link, architect);
    let raw = fs::read(readme).unwrap_or_default();
    let crlf = raw.windows(2).any(|w| w == b"\r\n");
    let current = String::from_utf8_lossy(&raw).replace("\r\n", "\n");
    let updated = splice(&current, &block);
    if updated == current {
        println!("  = {} up to date", readme.display());
        return Ok(false);
    }
    if check {
        return fail(format!(
            "{} is STALE - re-run `kairos harden` without --check",
            readme.display()
        ));
    }
    let payload = if crlf {
        updated.replace('\n', "\r\n")
    } else {
        updated
    };
    fs::write(readme, payload)?;
    println!("  + {} updated", readme.display());
    Ok(true)
}

/// Every `docs/plans/use-protection-please.md` under `root`, skipping build
/// and VCS directories, paired with its unit's README.
fn discover(root: &Path, out: &mut Vec<(PathBuf, PathBuf)>) {
    let Ok(entries) = fs::read_dir(root) else {
        return;
    };
    let mut dirs: Vec<PathBuf> = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();
        if path.is_dir() {
            if matches!(name.as_str(), "target" | "node_modules" | ".git" | "oracle") {
                continue;
            }
            dirs.push(path);
        } else if name == PLAN_NAME
            && root.file_name().is_some_and(|n| n == "plans")
            && root
                .parent()
                .and_then(Path::file_name)
                .is_some_and(|n| n == "docs")
        {
            if let Some(unit) = root.parent().and_then(Path::parent) {
                out.push((path, unit.join("README.md")));
            }
        }
    }
    dirs.sort();
    for d in dirs {
        discover(&d, out);
    }
}

pub(crate) fn main(root: &Path, _manifest: &Manifest, args: &[String]) -> Result<()> {
    let check = has_flag(args, "--check");
    let link = option(args, "--link").unwrap_or_default();
    let architect = option(args, "--architect").unwrap_or_default();
    let pairs: Vec<(PathBuf, PathBuf)> = if has_flag(args, "--all") {
        if !link.is_empty() {
            return fail("--link applies to a single --plan/--readme pair, not --all");
        }
        let mut found = Vec::new();
        discover(root, &mut found);
        if found.is_empty() {
            return fail(format!("no {PLAN_NAME} found under {}", root.display()));
        }
        found
    } else if let Some(plan) = option(args, "--plan") {
        let plan = PathBuf::from(plan);
        let readme = option(args, "--readme").map_or_else(
            || {
                plan.parent()
                    .and_then(Path::parent)
                    .and_then(Path::parent)
                    .map_or_else(|| PathBuf::from("README.md"), |u| u.join("README.md"))
            },
            PathBuf::from,
        );
        vec![(plan, readme)]
    } else {
        return fail("pass --plan FILE (with optional --readme FILE) or --all");
    };
    let mut failures = Vec::new();
    for (plan, readme) in pairs {
        if let Err(e) = process(&plan, &readme, check, &link, &architect) {
            failures.push(e.to_string());
        }
    }
    if failures.is_empty() {
        Ok(())
    } else {
        fail(format!(
            "harden: {} failure(s)\n{}",
            failures.len(),
            failures.join("\n")
        ))
    }
}
