//! `kairos patches` — each package repo's umbrella-only `.cargo/config.toml`.
//!
//! Inside the Kairos checkout every package repo patches the sibling crates
//! it actually uses to their local checkouts, so an edit in
//! `rusty_rtos_core` is visible in `rusty_rtos_kernel` without a push. The
//! table lives in EACH REPO's own (gitignored) `.cargo/config.toml`, never
//! in the umbrella's, and a repo lists only the crates in its dependency
//! graph. Standalone clones need none of this: they resolve siblings from
//! GitHub.
//!
//! # Why `[patch]` and not a `paths` override
//!
//! A `paths` override is tempting — it leaves `Cargo.lock` alone, so the
//! committed lockfile stays the standalone one — and it works for a single
//! leaf crate. It breaks the moment a package depends on a sibling
//! **facade**, because the facade's own dependency on its `-core` crate is
//! then overridden too, and cargo refuses to let an override alter a
//! package's dependency list: "path override for crate `rusty_rtos_kernel`
//! has altered the original list of dependencies ... in the future this
//! message will become a hard error". Kairos siblings are all facade +
//! core pairs, so `paths` is not available to this family. Measured on
//! 2026-09-09; the mission plan's decision log carries the row.
//!
//! # What that costs, and the rule it buys
//!
//! A `[patch]` rewrites `Cargo.lock`: the patched crate loses its git
//! `source` line. So the lockfile a developer sees inside the umbrella is
//! not the one a standalone clone resolves. The rule that keeps this
//! honest: **the committed lockfile is the standalone one** — the one a
//! fresh clone resolves from GitHub, which is what `Cargo.lock` is
//! committed for (hardening gate H-07) — and `cargo metadata --locked`
//! is therefore a standalone check, never an umbrella one. `kairos check`
//! does not pass `--locked` for that reason.
//!
//! The Janus wall this still avoids: an **unused** `[patch]` row becomes a
//! `[[patch.unused]]` lockfile entry whose ordering cargo does not keep
//! stable. This verb reads each package's manifests and emits a row only
//! for a crate the graph actually names.
//!
//! This verb replaces Janus's `tools/gen-sibling-patches.py`; the "who uses
//! whom" table lives in `KAIROS.toml` (`uses = [...]` per package).

use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
};

use crate::{Manifest, Package, Result, fail};

const HEADER: &str = "# Generated by `kairos patches` for the Kairos umbrella checkout: patch the
# sibling crates THIS repo actually depends on to their local checkouts, and
# nothing else. An unused [patch] row becomes a [[patch.unused]] lockfile entry
# whose ordering cargo does not keep stable (Janus mission plan section 8,
# wall 5), so this file lists only crates the manifests name. A `paths`
# override cannot be used here: it may not alter a package's dependency list,
# and every Kairos sibling is a facade over a -core crate.
#
# This rewrites Cargo.lock inside the umbrella. The COMMITTED lockfile is the
# standalone one a fresh clone resolves; `--locked` is a standalone check.
# Gitignored, for the same reason.
";

const IGNORE_NOTE: &str =
    "\n# Umbrella-only sibling overrides, generated by `kairos patches`\n/.cargo/config.toml\n";

/// Write the override file of every package that is checked out and lists
/// siblings under `uses`.
pub(crate) fn write_all(root: &Path, manifest: &Manifest, dry: bool) -> Result<()> {
    let mut written = 0usize;
    for package in &manifest.packages {
        let dir = root.join(&package.name);
        if !dir.join("Cargo.toml").is_file() {
            if !package.uses.is_empty() {
                println!("skip {}: not checked out", package.name);
            }
            continue;
        }
        if package.uses.is_empty() {
            continue;
        }
        let (text, entries) = render(root, manifest, package)?;
        let cargo_dir = dir.join(".cargo");
        let cfg = cargo_dir.join("config.toml");
        if dry {
            println!("would write {}:\n{text}", cfg.display());
            continue;
        }
        fs::create_dir_all(&cargo_dir)?;
        fs::write(&cfg, &text)?;
        let gitignore = dir.join(".gitignore");
        let existing = fs::read_to_string(&gitignore).unwrap_or_default();
        if !existing.contains("/.cargo/config.toml") {
            fs::write(&gitignore, format!("{existing}{IGNORE_NOTE}"))?;
        }
        println!("wrote {} ({entries} crate patch row(s))", cfg.display());
        written += 1;
    }
    if written == 0 && !dry {
        println!("patches: nothing to write (no checked-out package lists a sibling under `uses`)");
    }
    Ok(())
}

/// The manifests of a package: its workspace root and every `crates/*`.
/// `firmware/*` projects are excluded from the workspace and resolve on
/// their own, so they are not scanned.
fn manifests(dir: &Path, with_root: bool) -> Vec<PathBuf> {
    let mut out = Vec::new();
    if with_root {
        out.push(dir.join("Cargo.toml"));
    }
    if let Ok(entries) = fs::read_dir(dir.join("crates")) {
        for entry in entries.flatten() {
            let m = entry.path().join("Cargo.toml");
            if m.is_file() {
                out.push(m);
            }
        }
    }
    out
}

/// Every crate name that appears as a dependency key in `manifests`.
///
/// A dependency row is keyed by the crate name at the start of a line
/// (`rusty_rtos_core = { ... }`, `rusty_rtos_core.workspace = true`, or the
/// quoted form), or renamed with `package = "rusty_rtos_core"`.
fn dependency_names(manifests: &[PathBuf], into: &mut BTreeSet<String>) {
    for m in manifests {
        let Ok(text) = fs::read_to_string(m) else {
            continue;
        };
        for raw in text.lines() {
            let line = raw.trim_start();
            if line.starts_with('#') || line.starts_with('[') {
                continue;
            }
            if let Some(rest) = line.strip_prefix("package = \"") {
                if let Some((name, _)) = rest.split_once('"') {
                    into.insert(name.to_owned());
                }
                continue;
            }
            let key = line.trim_start_matches('"');
            let end = key.find([' ', '=', '.', '"']).unwrap_or(0);
            if end > 0 {
                if let Some(name) = key.get(..end) {
                    into.insert(name.to_owned());
                }
            }
        }
    }
}

/// Every sibling crate this package's graph can reach.
///
/// The package's own manifests name its direct siblings; a sibling's
/// `crates/*` manifests name what *it* pulls in — which is why a facade
/// (`rusty_rtos_kernel`) drags its own core (`rusty_rtos_kernel-core`) into
/// the table. Patching the facade without its core is the mistake that
/// silently links a local facade against a stale published core.
fn reachable_crate_names(root: &Path, manifest: &Manifest, package: &Package) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    dependency_names(&manifests(&root.join(&package.name), true), &mut names);
    let mut seen: BTreeSet<String> = BTreeSet::new();
    let mut queue: Vec<String> = package
        .uses
        .iter()
        .map(|u| u.split('/').next().unwrap_or(u).to_owned())
        .collect();
    while let Some(next) = queue.pop() {
        if !seen.insert(next.clone()) {
            continue;
        }
        let Some(sib) = manifest.packages.iter().find(|p| p.name == next) else {
            continue;
        };
        dependency_names(&manifests(&root.join(&sib.name), false), &mut names);
        for used in &sib.uses {
            queue.push(used.split('/').next().unwrap_or(used).to_owned());
        }
    }
    names
}

/// The patch-table text for one package, and how many rows it carries.
fn render(root: &Path, manifest: &Manifest, package: &Package) -> Result<(String, usize)> {
    let names = reachable_crate_names(root, manifest, package);
    let mut lines = vec![HEADER.to_owned()];
    let mut rows_total = 0usize;
    for used in &package.uses {
        let (sibling, only) = match used.split_once('/') {
            Some((s, c)) => (s, Some(c)),
            None => (used.as_str(), None),
        };
        let Some(sib) = manifest.packages.iter().find(|p| p.name == sibling) else {
            return fail(format!(
                "{}: uses {used:?} but {sibling:?} is not a listed package",
                package.name
            ));
        };
        let url = format!("https://github.com/{}/{}", manifest.kairos.org, sib.name);
        let mut rows = Vec::new();
        for krate in sib.crate_names() {
            if only.is_some_and(|c| c != krate) {
                continue;
            }
            if !names.contains(&krate) {
                continue;
            }
            let target = root.join(&sib.name).join("crates").join(&krate);
            // A sibling that is not checked out keeps its git dependency; a
            // row pointing at a directory that is not there makes cargo
            // refuse to resolve the graph at all.
            if !target.join("Cargo.toml").is_file() {
                eprintln!(
                    "  {}: {krate} is not checked out, keeping the git URL",
                    package.name
                );
                continue;
            }
            rows.push(format!(
                "{krate} = {{ path = \"../{}/crates/{krate}\" }}",
                sib.name
            ));
        }
        if rows.is_empty() {
            eprintln!(
                "  {}: uses {} but no manifest in its graph names one of its crates; no patch row",
                package.name, sib.name
            );
            continue;
        }
        rows_total = rows_total.saturating_add(rows.len());
        lines.push(format!("[patch.\"{url}\"]"));
        lines.extend(rows);
        lines.push(String::new());
    }
    Ok((lines.join("\n"), rows_total))
}
