//! `kairos patches` — each package repo's umbrella-only `.cargo/config.toml`.
//!
//! Inside the Kairos checkout every package repo overrides the sibling crates
//! it actually uses with their local checkouts, so an edit in
//! `rusty_rtos_core` is visible in `rusty_rtos_kernel` without a push. The
//! override lives in EACH REPO's own (gitignored) `.cargo/config.toml`, never
//! in the umbrella's, and a repo lists only the crates in its dependency
//! graph. Standalone clones need none of this: they resolve siblings from
//! GitHub.
//!
//! The mechanism is cargo's `paths` override, not a `[patch]` table. A
//! `[patch]` rewrites `Cargo.lock` (the patched crate loses its git `source`
//! and every unused row becomes a `[[patch.unused]]` entry whose order cargo
//! does not keep stable — the Janus mission plan's wall 5), so the lockfile a
//! developer commits from inside the umbrella is not the lockfile a standalone
//! clone or CI resolves. A `paths` override is applied after resolution: the
//! committed lockfile keeps the git source and commit, `cargo metadata
//! --locked` passes in both places, and an entry that matches nothing is
//! ignored. Cargo still fetches the sibling's git repository once to resolve
//! the graph, which is why the foundation repo is deployed first.
//!
//! This verb replaces Janus's `tools/gen-sibling-patches.py`; the "who uses
//! whom" table lives in `KAIROS.toml` (`uses = [...]` per package) and the
//! crate list is read from the package's own `Cargo.toml` files.

use std::{
    fs,
    path::{Path, PathBuf},
};

use crate::{Manifest, Package, Result, fail};

const HEADER: &str =
    "# Generated by `kairos patches` for the Kairos umbrella checkout: override the
# sibling crates THIS repo depends on with their local checkouts, and nothing
# else. This is cargo's `paths` override, applied after resolution, so the
# committed Cargo.lock keeps the siblings' git source and `--locked` passes
# here and in a standalone clone alike (a `[patch]` table would rewrite the
# lockfile; Janus mission plan section 8, wall 5). Gitignored: a standalone
# clone resolves the siblings from GitHub.
";

const IGNORE_NOTE: &str =
    "\n# Umbrella-only sibling overrides, generated by `kairos patches`\n/.cargo/config.toml\n";

/// Write the override file of every package that is checked out and lists
/// siblings under `uses`.
pub(crate) fn write_all(root: &Path, manifest: &Manifest, dry: bool) -> Result<()> {
    let mut written = 0usize;
    for package in &manifest.packages {
        let dir = root.join(&package.name);
        if !dir.join("Cargo.toml").is_file() {
            if !package.uses.is_empty() {
                println!("skip {}: not checked out", package.name);
            }
            continue;
        }
        if package.uses.is_empty() {
            continue;
        }
        let (text, entries) = render(root, manifest, package)?;
        let cargo_dir = dir.join(".cargo");
        let cfg = cargo_dir.join("config.toml");
        if dry {
            println!("would write {}:\n{text}", cfg.display());
            continue;
        }
        fs::create_dir_all(&cargo_dir)?;
        fs::write(&cfg, &text)?;
        let gitignore = dir.join(".gitignore");
        let existing = fs::read_to_string(&gitignore).unwrap_or_default();
        if !existing.contains("/.cargo/config.toml") {
            fs::write(&gitignore, format!("{existing}{IGNORE_NOTE}"))?;
        }
        println!("wrote {} ({entries} crate override(s))", cfg.display());
        written += 1;
    }
    if written == 0 && !dry {
        println!("patches: nothing to write (no checked-out package lists a sibling under `uses`)");
    }
    Ok(())
}

/// Every `Cargo.toml` of a package: the workspace root and `crates/*`.
/// `firmware/` projects are excluded from the workspace and resolve on their
/// own, so they are not scanned.
fn manifests(dir: &Path) -> Vec<PathBuf> {
    let mut out = vec![dir.join("Cargo.toml")];
    if let Ok(entries) = fs::read_dir(dir.join("crates")) {
        for entry in entries.flatten() {
            let m = entry.path().join("Cargo.toml");
            if m.is_file() {
                out.push(m);
            }
        }
    }
    out
}

/// Does any manifest of the package name `krate` as a dependency? A
/// dependency row is keyed by the crate name at the start of a line
/// (`rusty_rtos_core = { ... }`, `rusty_rtos_core.workspace = true`, or the
/// quoted form), or renamed with `package = "rusty_rtos_core"`.
fn depends_on(dir: &Path, krate: &str) -> bool {
    let renamed = format!("package = \"{krate}\"");
    for m in manifests(dir) {
        let Ok(text) = fs::read_to_string(&m) else {
            continue;
        };
        for raw in text.lines() {
            let line = raw.trim_start();
            if line.starts_with('#') {
                continue;
            }
            let key = line.trim_start_matches('"');
            if let Some(rest) = key.strip_prefix(krate) {
                let rest = rest.trim_start_matches('"');
                if rest.starts_with(' ') || rest.starts_with('=') || rest.starts_with('.') {
                    return true;
                }
            }
            if line.contains(&renamed) {
                return true;
            }
        }
    }
    false
}

/// The override file text for one package, and how many entries it carries.
fn render(root: &Path, manifest: &Manifest, package: &Package) -> Result<(String, usize)> {
    let dir = root.join(&package.name);
    let mut entries: Vec<String> = Vec::new();
    for used in &package.uses {
        let (sibling, only) = match used.split_once('/') {
            Some((s, c)) => (s, Some(c)),
            None => (used.as_str(), None),
        };
        let Some(sib) = manifest.packages.iter().find(|p| p.name == sibling) else {
            return fail(format!(
                "{}: uses {used:?} but {sibling:?} is not a listed package",
                package.name
            ));
        };
        for krate in sib.crate_names() {
            if only.is_some_and(|c| c != krate) {
                continue;
            }
            if !depends_on(&dir, &krate) {
                continue;
            }
            let target = root.join(&sib.name).join("crates").join(&krate);
            // A sibling that is not checked out keeps its git dependency.
            if !target.join("Cargo.toml").is_file() {
                eprintln!(
                    "  {}: {krate} is not checked out, keeping the git URL",
                    package.name
                );
                continue;
            }
            entries.push(format!("\"../{}/crates/{krate}\"", sib.name));
        }
        if only.is_none()
            && !entries
                .iter()
                .any(|e| e.contains(&format!("/{}/", sib.name)))
        {
            eprintln!(
                "  {}: uses {} but no manifest names one of its crates; nothing overridden",
                package.name, sib.name
            );
        }
    }
    let n = entries.len();
    let body = if entries.is_empty() {
        "paths = []\n".to_owned()
    } else {
        format!("paths = [\n    {},\n]\n", entries.join(",\n    "))
    };
    Ok((format!("{HEADER}\n{body}"), n))
}
